version: "3.8"
services:
  db:
    image: mysql:8
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root

  script:
    build: .
    image: dwellings:latest
    volumes:
      - ./main.py:/dwellings/main.py
    depends_on:
      - db
    env_file:
      - ./config.env
